<?php

namespace Container7DoeUG4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kg53ABHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Kg53ABH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Kg53ABH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'videoRepository' => ['privates', 'App\\Repository\\VideoRepository', 'getVideoRepositoryService', true],
            'videos' => ['privates', '.errored..service_locator.Kg53ABH.App\\Entity\\Video', NULL, 'Cannot autowire service ".service_locator.Kg53ABH": it references class "App\\Entity\\Video" but no such service exists.'],
        ], [
            'videoRepository' => 'App\\Repository\\VideoRepository',
            'videos' => 'App\\Entity\\Video',
        ]);
    }
}
